version: '3'

services:
   frontend:
      container_name: frontend
      build: .
      environment:
      - DATABASE_HOST=database
      - DATABASE_PORT=27017
      - DATABASE_NAME=realestate
      - DATABASE_USERNAME=user
      - DATABASE_PASSWORD=secretPassword
#      MONGODB_URI: mongodb://user:secretPassword@database/realestate
      ports:
        - "8080:5000"
      networks:
        - nodenw
      links:
        - database
   database:
      container_name: database
      image: mongo
      environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: root
        MONGO_INITDB_DATABASE: realestate
      ports:
        - "27017-27019:27017-27019"
      networks:
        - nodenw
      volumes:
        - ./db-init.js:/docker-entrypoint-initdb.d/init.js:ro
        - nodevolume:/data/db
   mongo-express:
      container_name: mongo-express
      image: mongo-express
      ports:
        - "8081:8081"
      environment:
        ME_CONFIG_MONGODB_ADMINUSERNAME: root
        ME_CONFIG_MONGODB_ADMINPASSWORD: root
      networks:
        - nodenw  
      links:
        - database
volumes:
  nodevolume:         
networks:
   nodenw:
     driver: bridge        